/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sap_businessone_dboperation_DataConvJNI */

#ifndef _Included_com_sap_businessone_dboperation_DataConvJNI
#define _Included_com_sap_businessone_dboperation_DataConvJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sap_businessone_dboperation_DataConvJNI
 * Method:    getRemainDays
 * Signature: ([BIJ)I
 */
JNIEXPORT jint JNICALL Java_com_sap_businessone_dboperation_DataConvJNI_getRemainDays
  (JNIEnv *, jclass, jbyteArray, jint, jlong);

/*
 * Class:     com_sap_businessone_dboperation_DataConvJNI
 * Method:    getCreateDateStr
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sap_businessone_dboperation_DataConvJNI_getCreateDateStr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sap_businessone_dboperation_DataConvJNI
 * Method:    isInTrail
 * Signature: (Ljava/lang/String;Z[B[BIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sap_businessone_dboperation_DataConvJNI_isInTrail
  (JNIEnv *, jclass, jstring, jboolean, jbyteArray, jbyteArray, jint, jlong);

/*
 * Class:     com_sap_businessone_dboperation_DataConvJNI
 * Method:    decrypt
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sap_businessone_dboperation_DataConvJNI_decrypt
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
